application:
  name: coletor-shipay

#############################################################################
## Profile configuration
#############################################################################

spring:
  config:
    activate:
      on-profile: prd

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, scheduledtasks

#############################################################################
## Server configuration
#############################################################################

server:
  port: ${PORT:8085}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json

#############################################################################
## Datasource configuration
#############################################################################


  datasource:
    driver-class-name: org.postgresql.Driver

r2dbc:
  url: {{R2DBC_URL}}
  host: {{R2DBC_HOST}}
  port: {{R2DBC_PORT}}
  database: {{R2DBC_DATABASE}}
  username: {{R2DBC_USER}}
  password: {{R2DBC_PASS}}
  properties:
    schema: {{R2DBC_SCHEMA}}

pool:
  enabled: true
  initial-size: 5000
  max-size: 8000
  max-idle-time: 10000
  max-active: 8000

#############################################################################
## Management configuration
#############################################################################

logging:
  level:
    io.r2dbc.spi: DEBUG
    org.springframework.r2dbc.core: DEBUG


integration:
  shipay:
    url: {{INTEGRATION_URL}}
    auth:
      access-key: {{INTEGRATION_KEY}}
      pos-product-id: {{INTEGRATION_ID}}


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true
  circuitbreaker:
    enabled: true
  retry:
    maxAttempts: 2
    delay:
      initial: 1000
      max: 1
  threadpool:
    default:
      coreSize: 50
      maximumSize: 150
      maxQueueSize: 1900


#############################################################################
## Scheduler configuration
#############################################################################

scheduler:
  cron: "0 0/5 * * * ?"
  thread:
    pool:
      size: 10 #${THREAD_POOL_SIZE}

pod:
  name: pod-local-1
