package br.com.destaxa.v8.coletor.shipay.application.dto.request.psp;

public enum ReconciliationPSPEnum {
  
   RECONCILIATION_DOWNWARD ,
       RECONCILIATION_SALES ,
       RECONCILIATION_PIX_ORIGINAL ,
       RECONCILIATION_PIX_TBANKS ,
       RECONCILIATION_PIX_ITAU ,
       RECONCILIATION_PIX_ITAU_ANY_BANK ,
       RECONCILIATION_PIX_ITAU_ANY_BANK_V2 ,
       RECONCILIATION_PIX_PORTO_BANK ,
       RECONCILIATION_PIX_PICPAY_ANY_BANK ,
       RECONCILIATION_PIX_SHIPAY_PAGADOR_ANY_BANK 
  
  
}
