version: '3.5'

services:
  gthb-plan:
    container_name: gthb-shipay-colector
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sa}
      PGDATA: /data/postgres
      POSTGRES_DB: gthb_conciliation
    volumes:
      - gthbshipay:/data/postgres
    ports:
      - "45440:45432"
    networks:
      - gthbshipay
    restart: unless-stopped

networks:
  gthbplan:
    driver: bridge
volumes:
  gthbplan:
