version: '3.5'

services:
  destaxa-plan:
    container_name: destaxa-shipay-colector
    image: postgres:13.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sa}
      PGDATA: /data/postgres
      POSTGRES_DB: destaxa_conciliation
    volumes:
      - destaxashipay:/data/postgres
    ports:
      - "45440:45432"
    networks:
      - destaxashipay
    restart: unless-stopped

networks:
  destaxaplan:
    driver: bridge
volumes:
  destaxaplan:
